### ISSUE TITLE
Eselect-Repository/readme.md

### ISSUE THREAD

**Issue by necrose99** [prototype99/prototype99#71]
`eselect repository add prototype99 git https://github.com/prototype99/prototype99.git`
[](https://wiki.gentoo.org/wiki/Eselect/Repository)
adds a repos.conf entry 

`pentoo /usr/src/rogauracore/prototype # eselect repository enable prototype99
error: prototype99: repository not in repositories.xml
pentoo /usr/src/rogauracore/prototype # eselect repository add prototype99 git https://github.com/prototype99/prototype99.git
Adding prototype99 to /etc/portage/repos.conf/eselect-repo.conf ...
Repository prototype99 added
pentoo /usr/src/rogauracore/prototype # emerge --sync prototype99
>>> Syncing repository 'prototype99' into '/var/db/repos/prototype99'...
/usr/bin/git clone --depth 1 https://github.com/prototype99/prototype99.git .
Cloning into '.'...
remote: Enumerating objects: 4441, done.
remote: Counting objects: 100% (4441/4441), done.
remote: Compressing objects: 100% (3374/3374), done.
remote: Total 4441 (delta 897), reused 4177 (delta 872), pack-reused 0
Receiving objects: 100% (4441/4441), 12.62 MiB | 12.29 MiB/s, done.
Resolving deltas: 100% (897/897), done.
=== Sync completed for prototype99' 
`

**Comment by prototype99** [comment]
oh terribly sorry! my new git client doesn't seem to have support for issues (for some reason), so I generally have to check manually. I think I've made the change you requested, but if not please do be sure to let me know. I'll try and remember to check back in about a week

**Comment by necrose99** [comment]
Yup , 
https://github.com/goose121/initify
Transmogrify sysd units to OPENRC...
