### ISSUE TITLE
new update on media-gfx/flameshot

### ISSUE THREAD

**Issue by brilliant116** [prototype99/prototype99#72]
there is a new version of flameshot software. Could you update this, appreciate for your work.
The latest releaseis here. https://github.com/flameshot-org/flameshot/releases

**Comment by prototype99** [comment]
Wow, they have been busy! I don't personally use flameshot any more, but I have made an ebuild you can try, if there are any issues let me know and I'll look into it

**Comment by prototype99** [comment]
assuming it's good
